{% set name = "source" %}
{% set version = "1.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/fair-ease/Source/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 2c29f71fe34c6ea6bf45d1bf10340a5dc901bbcf4830d5f892d7bee5ad4f0178

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry-core

  run:
    - python >={{ python_min }}
    - pykml
    - lxml
    - numpy
    - pandas
    - netcdf4
    - seawater
    - scipy
    - scikit-learn
    - unidecode

test:
  requires:
    - python {{ python_min }}
  imports:
    - SOURCE


about:
  home: https://github.com/fair-ease/Source
  license: CC-BY-NC-SA-4.0
  license_file: LICENSE.txt
  summary: The package Sea Observations Utility for Reprocessing, Calibration and Evaluation (SOURCE) aims to manage jobs with in situ observations and model data from Ocean General Circulation Models (OGCMs)

extra:
  recipe-maintainers:
    - marie59
